# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
instance_class: F2

automatic_scaling:
  max_num_instances: 1

network:
  session_affinity: true

