package ch.uzh.ifi.hase.soprafs24.constant;

public enum MessageType {

    CHAT, CHAT_INGAME, CHAT_INGAME_CORRECT, JOIN, LEAVE, LEAVE_CREATOR, POINTS, START_COUNTDOWN, JOKER, TIMER, LOGOUT, LOGOUT_CREATOR, PLAYED, PLAY_AGAIN, JS, PLAYERS
}
